"""Idempotent, dry-run-by-default SQLite to PostgreSQL copier."""

import argparse
import os
from datetime import datetime, timezone

from sqlalchemy import BigInteger, Integer, MetaData, create_engine, func, select, text


def normalize_row(table_name, row, target_table):
    """Adapt older SQLite rows to the current production schema."""
    payload = {k: v for k, v in row.items() if k in target_table.c}
    backfilled = []

    if table_name == "jobs":
        now = datetime.now(timezone.utc)

        created_at = (
            row.get("created_at")
            or row.get("discovered_at")
            or row.get("updated_at")
            or now
        )

        discovered_at = (
            row.get("discovered_at")
            or created_at
        )

        updated_at = (
            row.get("updated_at")
            or discovered_at
            or created_at
        )

        if not payload.get("first_seen_at"):
            payload["first_seen_at"] = discovered_at
            backfilled.append("first_seen_at")

        if not payload.get("last_seen_at"):
            payload["last_seen_at"] = updated_at
            backfilled.append("last_seen_at")

        if not payload.get("last_verified_at"):
            payload["last_verified_at"] = updated_at
            backfilled.append("last_verified_at")

        if not payload.get("posting_status"):
            payload["posting_status"] = "UNKNOWN"
            backfilled.append("posting_status")

    # Never explicitly insert NULL into a NOT NULL column when the
    # production database has a default that can safely supply it.
    for column in target_table.columns:
        if (
            column.name in payload
            and payload[column.name] is None
            and not column.nullable
            and column.server_default is not None
        ):
            payload.pop(column.name)
            backfilled.append(f"{column.name}:server_default")

    # Fail with a useful message if an old database contains another
    # required value for which no safe migration rule exists.
    for column in target_table.columns:
        if column.name not in payload:
            if column.nullable or column.server_default is not None:
                continue

            # Autogenerated primary keys may safely be omitted.
            if column.primary_key and column.autoincrement:
                continue

            raise ValueError(
                f"Cannot safely migrate {table_name}: "
                f"required target column '{column.name}' has no value "
                f"and no migration/default rule."
            )

        if payload[column.name] is None and not column.nullable:
            raise ValueError(
                f"Cannot safely migrate {table_name}: "
                f"required target column '{column.name}' is NULL."
            )

    return payload, backfilled


def advance_postgres_sequences(connection, tables):
    """Align serial/identity sequences after preserving historical integer IDs."""
    if connection.dialect.name != "postgresql":
        return {}
    advanced = {}
    for table in tables:
        primary_keys = list(table.primary_key.columns)
        if len(primary_keys) != 1 or not isinstance(primary_keys[0].type, (Integer, BigInteger)):
            continue
        column = primary_keys[0]
        sequence = connection.scalar(
            text("SELECT pg_get_serial_sequence(:table_name, :column_name)"),
            {"table_name": table.fullname, "column_name": column.name},
        )
        if not sequence:
            continue
        maximum = connection.scalar(select(func.max(column)))
        if maximum is None:
            connection.execute(
                text("SELECT setval(CAST(:sequence AS regclass), 1, false)"),
                {"sequence": sequence},
            )
            advanced[table.name] = 0
        else:
            connection.execute(
                text("SELECT setval(CAST(:sequence AS regclass), :maximum, true)"),
                {"sequence": sequence, "maximum": int(maximum)},
            )
            advanced[table.name] = int(maximum)
    return advanced


def migrate(source, target, execute=False):
    source_meta = MetaData();source_meta.reflect(bind=source)
    target_meta = MetaData();target_meta.reflect(bind=target)
    summary = {}
    migrated_tables = []
    with source.connect() as src, target.begin() as dst:
        for table in source_meta.sorted_tables:
            if table.name not in target_meta.tables:
                continue
            try:
                rows = [dict(row) for row in src.execute(select(table)).mappings()]
                target_table = target_meta.tables[table.name]
                pk = [column.name for column in target_table.primary_key.columns]
                summary[table.name] = {"source_rows":len(rows),"would_insert":0,"backfilled_fields":{}}
                for row in rows:
                    exists=False
                    if pk and all(row.get(name) is not None for name in pk):
                        exists=dst.execute(select(target_table).where(*[target_table.c[name]==row[name] for name in pk])).first() is not None
                    if exists:continue
                    payload,backfilled=normalize_row(table.name,row,target_table)
                    summary[table.name]["would_insert"]+=1
                    for field in backfilled:
                        fields=summary[table.name]["backfilled_fields"];fields[field]=fields.get(field,0)+1
                    if execute:dst.execute(target_table.insert().values(**payload))
                migrated_tables.append(target_table)
            except Exception as exc:
                raise RuntimeError(f"Migration failed for table '{table.name}': {exc}") from exc
        summary["_sequences"] = advance_postgres_sequences(dst,migrated_tables) if execute else {}
    return summary


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        default="sqlite:///./nick_job_agent.db",
    )
    parser.add_argument("--target",default=os.environ.get("DATABASE_URL"))
    parser.add_argument("--execute", action="store_true")
    args = parser.parse_args()

    if not args.target:parser.error("--target or DATABASE_URL is required")
    source=create_engine(args.source);target=create_engine(args.target)
    summary=migrate(source,target,args.execute)

    print(
        {
            "mode": "execute" if args.execute else "dry-run",
            "tables": summary,
        }
    )


if __name__ == "__main__":
    main()
