"use client";
import Link from "next/link";
import {useState} from "react";
import {apiFetch} from "@/lib/client-api";
import {AgentRun,JobResearchReport,SemanticFitReport} from "@/lib/types";

export default function AIAnalysisPanel({jobId,deterministicScore,initialAnalysis,initialResearch,initialRuns}:{jobId:number;deterministicScore:number|null;initialAnalysis:SemanticFitReport|null;initialResearch:JobResearchReport|null;initialRuns:AgentRun[]}){
 const [analysis,setAnalysis]=useState(initialAnalysis);const [research,setResearch]=useState(initialResearch);const [runs,setRuns]=useState(initialRuns);const [status,setStatus]=useState("");const [showTrace,setShowTrace]=useState(false);
 async function refreshRuns(){const response=await apiFetch(`/jobs/${jobId}/agent-runs`);if(response.ok)setRuns(await response.json())}
 async function analyze(){setStatus("Running semantic analysis...");const response=await apiFetch(`/jobs/${jobId}/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refresh:false})});const body=await response.json();if(body.report){setAnalysis(body.report);setStatus(body.report.cache_hit?"Loaded cached analysis":"Analysis complete")}else setStatus(`Deterministic baseline retained: ${body.error??"LLM unavailable"}`);await refreshRuns()}
 async function researchRole(){setStatus("Researching permitted public context...");const response=await apiFetch(`/jobs/${jobId}/research`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refresh:false})});const body=await response.json();if(body.report){setResearch(body.report);setStatus(body.report.cache_hit?"Loaded cached research":"Research complete")}else setStatus(body.error??"Research unavailable");await refreshRuns()}
 return <section className="ai-intelligence">
  <div className="ai-actions"><button onClick={analyze}>AI ANALYZE</button><button onClick={researchRole}>RESEARCH ROLE</button><span role="status">{status}</span></div>
  <div className="score-comparison"><div><span>DETERMINISTIC FIT</span><strong>{deterministicScore??"--"}</strong></div><div><span>SEMANTIC FIT</span><strong>{analysis?.semantic_fit_score??"--"}</strong></div><div><span>BLENDED</span><strong>{analysis?.blended_score??"--"}</strong></div></div>
  {analysis?<section className="panel semantic-panel"><p className="panel-label">EVIDENCE-GROUNDED AI ANALYSIS</p><h2>{analysis.reasoning_summary}</h2><h3>Validated strengths</h3>{analysis.strengths.map((strength,index)=><article className="cited-strength" key={`${strength.statement}-${index}`}><p>{strength.statement}</p><div>Evidence: {strength.evidence_ids.map(id=><Link href={`/profile#${id}`} key={id}>{id}</Link>)}</div></article>)}<h3>Gaps and uncertainty</h3><ul>{[...analysis.gaps,...analysis.requirement_gaps].map((gap,index)=><li key={`${gap}-${index}`}>{gap}</li>)}</ul>{analysis.unsupported_claims.length?<div className="unsupported"><b>Removed unsupported claims</b><ul>{analysis.unsupported_claims.map(x=><li key={x}>{x}</li>)}</ul></div>:null}<details><summary>Model metadata</summary><dl><div><dt>Provider</dt><dd>{analysis.provider}</dd></div><div><dt>Model</dt><dd>{analysis.model}</dd></div><div><dt>Prompt</dt><dd>{analysis.prompt_version}</dd></div><div><dt>Latency</dt><dd>{analysis.latency_ms} ms</dd></div><div><dt>Evidence used</dt><dd>{analysis.evidence_ids.length}</dd></div><div><dt>Tokens</dt><dd>{analysis.input_tokens} in / {analysis.output_tokens} out / {analysis.cached_tokens} cached</dd></div></dl></details></section>:null}
  {research?<section className="panel research-panel"><p className="panel-label">ATTRIBUTED ROLE RESEARCH</p><h2>Company context</h2><p>{research.company_summary}</p><h3>Role context</h3><p>{research.role_summary}</p><h3>Potential risks</h3><ul>{research.potential_risks.map(x=><li key={x}>{x}</li>)}</ul><h3>Sources</h3><ul>{research.source_citations.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> <small>{source.source_type}</small></li>)}</ul></section>:null}
  <button className="trace-toggle" onClick={()=>setShowTrace(!showTrace)}>AGENT TRACE</button>{showTrace?<section className="panel trace-panel">{runs.length?runs.map(run=><article key={run.id}><b>{run.agent_type} / {run.status}</b>{run.actions_json.map((action,index)=><p key={index}>Step {action.step??index+1}: {action.tool??"action"} - {action.status??"recorded"}</p>)}{run.errors_json.map((error,index)=><p className="trace-error" key={index}>{error.error}</p>)}</article>):<p>No agent runs recorded.</p>}</section>:null}
 </section>
}
