"use client";
import Link from "next/link";
import {useState} from "react";
import {API_URL} from "@/lib/api";
import {apiFetch} from "@/lib/client-api";
import {ApplicationPackage} from "@/lib/types";
const defaultQuestions=["Why are you interested in this role?","What experience makes you a strong fit?","Describe your experience with search, retrieval, or ranking.","Describe a technically difficult ML problem you worked on.","Will you now or in the future require employment visa sponsorship?"];
export default function ApplicationPackagePanel({jobId,initialPackage}:{jobId:number;initialPackage:ApplicationPackage|null}){
 const [pkg,setPkg]=useState(initialPackage);const [questions,setQuestions]=useState(defaultQuestions.join("\n"));const [status,setStatus]=useState("");
 async function build(force=false){setStatus("Generating grounded draft...");const items=questions.split("\n").map(x=>x.trim()).filter(Boolean).map(question_text=>({question_text,required:true,answer_length:"MEDIUM",source:"manual"}));const response=await apiFetch(`/jobs/${jobId}/application-package${force?"/regenerate":""}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questions:items,force,cover_letter_requested:false,resume_pages:2})});const body=await response.json();if(body.package)setPkg(body.package);setStatus(body.error??body.status)}
 async function review(){setStatus("ReviewerAgent validating...");const response=await apiFetch(`/jobs/${jobId}/application-package/review`,{method:"POST"});const body=await response.json();if(body.package)setPkg(body.package);setStatus(body.error??body.status)}
 async function approve(){const response=await apiFetch(`/jobs/${jobId}/application-package/approve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({artifact:"package",save_reusable_answers:false})});if(response.ok){setPkg(await response.json());setStatus("Approved for future preparation - nothing submitted")}else setStatus("Package must pass review before approval")}
 async function editAnswer(id:string,current:string){const answer=window.prompt("Edit answer. Material changes require revalidation.",current);if(answer===null)return;const response=await apiFetch(`/jobs/${jobId}/application-package/answers/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({answer})});if(response.ok)setPkg(await response.json())}
 async function editBullet(id:string,current:string){const text=window.prompt("Edit bullet. Material changes require revalidation.",current);if(text===null)return;const response=await apiFetch(`/jobs/${jobId}/application-package/resume-bullets/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(response.ok)setPkg(await response.json())}
 return <section className="panel application-package"><p className="panel-label">APPLICATION PACKAGE</p><div className="package-heading"><div><h2>Evidence-grounded package</h2><p>Approval enables controlled browser preparation; it never submits by itself.</p></div><b>{pkg?.status??"NOT GENERATED"}</b></div><details className="question-input"><summary>ADD APPLICATION QUESTIONS</summary><textarea aria-label="Application questions, one per line" value={questions} onChange={e=>setQuestions(e.target.value)} rows={7}/><small>One question per line. Unknown legal, salary, date, relocation, and identity fields require human review.</small></details><div className="ai-actions"><button type="button" onClick={()=>build(false)}>BUILD APPLICATION</button>{pkg?<><button type="button" onClick={review}>RUN REVIEWER</button><button type="button" onClick={()=>build(true)}>REGENERATE</button><button type="button" onClick={approve}>APPROVE PACKAGE</button>{pkg.tailored_resume_preview.bullets[0]?<button type="button" onClick={()=>editBullet(pkg.tailored_resume_preview.bullets[0].id,pkg.tailored_resume_preview.bullets[0].edited_text??pkg.tailored_resume_preview.bullets[0].generated_text)}>EDIT RESUME BULLET</button>:null}</>:null}<span role="status">{status}</span></div>
 {pkg?<><div className="package-grid"><section><h3>Application Strategy</h3><strong>{pkg.resume_strategy.primary_positioning}</strong><ul>{pkg.resume_strategy.top_3_themes.map(x=><li key={x}>{x}</li>)}</ul><h4>Known gaps</h4><ul>{pkg.resume_strategy.known_gaps.map(x=><li key={x}>{x}</li>)}</ul></section><section><h3>Tailored Resume</h3><a href={`${API_URL}/jobs/${jobId}/application-package/tailored-resume/download`}>DOWNLOAD PDF</a><p>{pkg.resume_version_id}</p><small>Original master resume remains unchanged.</small></section></div><details open><summary>RESUME CHANGES &amp; PROVENANCE</summary>{pkg.tailored_resume_preview.bullets.map(b=><article className="resume-change" key={b.id}><b>{b.transformation_type} / {b.employer_or_context}</b><p><small>Source:</small> {b.source_resume_text}</p><p><small>Tailored:</small> {b.edited_text??b.generated_text}</p><p>Evidence: {b.source_evidence_ids.map(id=><Link href={`/profile#${id}`} key={id}>{id} </Link>)}</p><em>{b.validation_status} ({Math.round(b.validation_confidence*100)}%)</em></article>)}</details><details open><summary>APPLICATION ANSWERS</summary>{pkg.application_answers.map(a=><article className={a.requires_human_review?"answer review-needed":"answer"} key={a.id}><h4>{a.question_text}</h4><p>{a.answer??"INSUFFICIENT_EVIDENCE / HUMAN REVIEW REQUIRED"}</p><p><small>{a.answer_type} / {a.answer_status}</small></p><button type="button" onClick={()=>editAnswer(a.id,a.answer??"")}>EDIT DRAFT</button>{a.evidence_ids.length?<p>Evidence: {a.evidence_ids.join(", ")}</p>:null}</article>)}</details><details><summary>COVER LETTER</summary><p>{pkg.cover_letter??(pkg.resume_strategy.cover_letter_recommended?"Not generated":"Not recommended for this package")}</p></details><details open><summary>REVIEWER FINDINGS</summary><p>Status: {pkg.review_status??"Not reviewed"}</p>{pkg.review_findings.length?<ul>{pkg.review_findings.map((x,i)=><li key={i}><b>{x.severity}</b> {x.claim} - {x.recommended_action}</li>)}</ul>:<p>No findings recorded.</p>}{pkg.unsupported_claims_removed.length?<><h4>Unsupported claims removed</h4><ul>{pkg.unsupported_claims_removed.map(x=><li key={x}>{x}</li>)}</ul></>:null}</details><details><summary>COST / MODEL METADATA</summary><p>{pkg.provider} / {pkg.model}</p><p>{pkg.input_tokens} input / {pkg.output_tokens} output / {pkg.cached_tokens} cached</p><p>${pkg.estimated_cost.toFixed(6)} / {pkg.latency_ms} ms</p><p>Evidence records used: {pkg.evidence_ids_used.length}</p></details></>:null}</section>
}
