"use client";
import {useState} from "react";
import {apiFetch} from "@/lib/client-api";
import {ApplicationSettings,ApplicationSummary} from "@/lib/types";
export default function AutoApplySettings({initialSettings,summary}:{initialSettings:ApplicationSettings|null;summary:ApplicationSummary|null}){
 const [settings,setSettings]=useState(initialSettings);const [saving,setSaving]=useState(false);if(!settings)return null;
 async function update(next:ApplicationSettings){setSaving(true);const response=await apiFetch(`/application-settings`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(response.ok)setSettings(await response.json());setSaving(false)}
 return <section className="auto-apply-panel"><div><p className="eyebrow">APPLICATION OPERATIONS</p><h2>Auto apply <b className={settings.auto_submit_enabled?"on":"off"}>{settings.auto_submit_enabled?"ON":"OFF"}</b></h2><p>Standing authorization is local and explicit. Moderate-fit roles remain eligible; safety blockers never are.</p></div><div className="auto-controls"><label>Mode<select value={settings.application_mode} disabled={saving} onChange={e=>update({...settings,application_mode:e.target.value as ApplicationSettings["application_mode"]})}><option value="manual">manual</option><option value="fill_only">fill_only</option><option value="auto_submit">auto_submit</option></select></label><label className="toggle"><input type="checkbox" checked={settings.auto_submit_enabled} disabled={saving} onChange={e=>update({...settings,auto_submit_enabled:e.target.checked})}/> Standing authorization</label><button className={settings.auto_apply_paused?"primary-action":""} onClick={()=>update({...settings,auto_apply_paused:!settings.auto_apply_paused})}>{settings.auto_apply_paused?"RESUME AUTONOMY":"PAUSE AUTONOMY"}</button><span>Daily cap {settings.policy.daily_application_cap} · Company cap {settings.policy.company_daily_cap}</span></div><div className="application-metrics">{summary?Object.entries(summary).filter(([key])=>key!=="estimated_llm_cost").map(([key,value])=><span key={key}><b>{value}</b>{key.replaceAll("_"," ")}</span>):null}</div></section>
}
