"use client";
import {FormEvent,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {Building2,Radar} from "lucide-react";
import {API_URL} from "@/lib/api";
import {Company} from "@/lib/types";
export default function CompanyManager({companies}:{companies:Company[]}){
 const router=useRouter();const [pending,startTransition]=useTransition();const [show,setShow]=useState(false);const [status,setStatus]=useState("");
 async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch(`${API_URL}/companies`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),website_url:form.get("website")||null,careers_url:form.get("careers")||null,company_type:form.get("type"),priority:form.get("priority"),enabled:true})});setStatus(response.ok?"Company added":"Could not add company");if(response.ok){setShow(false);startTransition(()=>router.refresh())}}
 async function detect(id:number){setStatus("Inspecting public careers page…");const response=await fetch(`${API_URL}/companies/${id}/detect`,{method:"POST"});const data=await response.json();setStatus(response.ok?`Detected ${data.detected_ats} (${Math.round(data.confidence*100)}% confidence)`:data.detail??"Detection failed");if(response.ok)startTransition(()=>router.refresh())}
 return <div className="company-manager"><div className="source-heading"><div><h2>Company registry</h2><span>{companies.length} companies</span></div><button onClick={()=>setShow(x=>!x)}>ADD COMPANY</button></div>{status?<p className="status-line" role="status">{status}</p>:null}{show?<form className="source-form company-form" onSubmit={add}><label>Name<input name="name" required/></label><label>Website<input name="website" type="url"/></label><label>Careers URL<input name="careers" type="url" required/></label><label>Type<select name="type"><option>AI_STARTUP</option><option>TECH_STARTUP</option><option>RESEARCH_LAB</option><option>LARGE_TECH</option><option>MID_SIZE_TECH</option><option>OTHER</option></select></label><label>Priority<select name="priority"><option>HIGH</option><option>NORMAL</option><option>LOW</option></select></label><button disabled={pending}>SAVE</button></form>:null}<section className="company-grid">{companies.map(company=><article className="panel company-card" key={company.id}><div className="company-title"><Building2 size={18}/><div><h3>{company.name}</h3><span>{company.company_type} · {company.priority}</span></div></div><dl><div><dt>Careers</dt><dd>{company.careers_url??"Not configured"}</dd></div><div><dt>Detected ATS</dt><dd>{company.detected_ats??"Not detected"}</dd></div><div><dt>Sources</dt><dd>{company.source_count}</dd></div><div><dt>Last scan</dt><dd>{company.last_scan?new Date(company.last_scan).toLocaleString():"Never"}</dd></div></dl><button className="detect-button" onClick={()=>detect(company.id)}><Radar size={14}/> DETECT JOB SYSTEM</button></article>)}</section></div>
}
