"use client";

import {FormEvent,useEffect,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {Building2,RefreshCw,Search} from "lucide-react";
import {apiFetch} from "@/lib/client-api";
import {CareerRun,JobSource} from "@/lib/types";

export default function FindJobsPanel({sources,initialRun}:{sources:JobSource[];initialRun:CareerRun|null}){
 const router=useRouter();const [pending,startTransition]=useTransition();const [run,setRun]=useState(initialRun);const [adding,setAdding]=useState(false);const [message,setMessage]=useState("");
 const active=run?.status==="queued"||run?.status==="running";
 useEffect(()=>{if(!active)return;const timer=window.setInterval(async()=>{try{const response=await apiFetch(`/career-intelligence/runs/${run.id}`);if(!response.ok){setMessage("Could not refresh analysis progress.");return}const value=await response.json() as CareerRun;setRun(value);if(value.status==="completed"||value.status==="failed")startTransition(()=>router.refresh())}catch{setMessage("Career Agent lost contact with the local API. It will keep checking.")}},4000);return()=>window.clearInterval(timer)},[active,run?.id,router]);
 async function find(){setMessage("");const response=await apiFetch("/career-intelligence/find-jobs",{method:"POST"});const body=await response.json();if(!response.ok){setMessage(body.detail??"Could not start job discovery");return}setRun(body as CareerRun)}
 async function addSource(event:FormEvent<HTMLFormElement>){event.preventDefault();setAdding(true);setMessage("Inspecting the public career page...");const form=new FormData(event.currentTarget);try{const response=await apiFetch("/sources/detect-and-create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({company:form.get("company"),careers_url:form.get("careers_url")})});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Source setup failed");setMessage(`${body.company} added (${body.ats_type}).`);startTransition(()=>router.refresh());event.currentTarget.reset()}catch(error){setMessage(error instanceof Error?error.message:"Source setup failed")}finally{setAdding(false)}}
 const steps=[{label:"Jobs found",value:run?.jobs_found??0},{label:"New unique jobs",value:run?.unique_jobs??0},{label:"Promising",value:run?.promising_jobs??0},{label:"AI analyzed",value:`${run?.semantic_completed??0} / ${run?.semantic_selected??0}`},{label:"Ranked",value:run?.ranked_jobs??0}];
 return <section className="find-jobs panel"><div className="find-jobs-heading"><div><p className="panel-label">FIND JOBS</p><h2>Turn your approved profile into ranked opportunities.</h2><p>Scans only the public company sources you configure. AI analysis is bounded and may use provider credits.</p></div><button className="cta" type="button" disabled={pending||active||!sources.length} onClick={find}><Search size={16}/>{active?"FINDING JOBS...":"FIND JOBS"}</button></div>
 {!sources.length?<div className="first-source"><div><Building2 size={20}/><h3>Add your first company</h3><p>Paste a public careers page. Career Agent will detect a supported ATS when possible.</p></div><form onSubmit={addSource}><input name="company" aria-label="Company name" placeholder="Company name" required/><input name="careers_url" aria-label="Public careers page URL" type="url" placeholder="https://company.com/careers" required/><button type="submit" disabled={adding}>{adding?"DETECTING...":"ADD COMPANY"}</button></form></div>:<div className="configured-sources"><span>{sources.length} enabled source{sources.length===1?"":"s"}</span>{sources.slice(0,4).map(source=><b key={source.id}>{source.company}</b>)}</div>}
 {run?<><div className="intelligence-progress">{steps.map(step=><div key={step.label}><span>{step.label}</span><strong>{step.value}</strong></div>)}</div><p className={`status-line ${run.status}`} role="status"><RefreshCw size={14}/>{run.message}{run.provider?` · ${run.provider}/${run.model} · $${run.estimated_cost.toFixed(4)}`:" · deterministic scoring remains available"}</p></>:null}{message?<p className="status-line" role="status">{message}</p>:null}</section>
}
