"use client";

import {FormEvent,useEffect,useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {Building2,RefreshCw,Search} from "lucide-react";
import {apiFetch} from "@/lib/client-api";
import {CareerRun,JobSource} from "@/lib/types";

export default function FindJobsPanel({sources,initialRun}:{sources:JobSource[];initialRun:CareerRun|null}){
 const router=useRouter();const [pending,startTransition]=useTransition();const [run,setRun]=useState(initialRun);const [adding,setAdding]=useState(false);const [message,setMessage]=useState("");const [pollingStopped,setPollingStopped]=useState(false);const pollFailures=useRef(0);
 const active=(run?.status==="queued"||run?.status==="running")&&!pollingStopped;
 useEffect(()=>{if(!active)return;const poll=async()=>{try{const response=await apiFetch(`/career-intelligence/runs/${run.id}`);if(!response.ok)throw new Error("progress unavailable");const value=await response.json() as CareerRun;pollFailures.current=0;setMessage("");setRun(value);if(value.status==="completed"||value.status==="failed")startTransition(()=>router.refresh())}catch{pollFailures.current+=1;if(pollFailures.current>=5){setPollingStopped(true);setMessage("RoleCall could not confirm that discovery is still running. Refresh the server state, then retry if needed.")}else setMessage("RoleCall temporarily lost contact with the local API. Reconnecting...")}};void poll();const timer=window.setInterval(poll,4000);return()=>window.clearInterval(timer)},[active,run?.id,router]);
 async function find(){setMessage("");setPollingStopped(false);pollFailures.current=0;try{const response=await apiFetch("/career-intelligence/find-jobs",{method:"POST"});const body=await response.json();if(!response.ok){setMessage(body.detail??"Could not start job discovery");return}setRun(body as CareerRun)}catch{setMessage("RoleCall could not reach the local API. Check that the backend is running, then try again.")}}
 async function addSource(event:FormEvent<HTMLFormElement>){event.preventDefault();setAdding(true);setMessage("Inspecting the public career page...");const form=new FormData(event.currentTarget);try{const response=await apiFetch("/sources/detect-and-create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({company:form.get("company"),careers_url:form.get("careers_url")})});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Source setup failed");setMessage(`${body.company} added (${body.ats_type}).`);startTransition(()=>router.refresh());event.currentTarget.reset()}catch(error){setMessage(error instanceof Error?error.message:"Source setup failed")}finally{setAdding(false)}}
 const count=(value:number|undefined)=>new Intl.NumberFormat("en-US").format(value??0);
 const steps=[{label:"Sources",value:run?`${run.sources_succeeded??0} / ${run.source_count??0}`:"0"},{label:"Public jobs considered",value:count(run?.jobs_found)},{label:"New unique jobs",value:count(run?.unique_jobs)},{label:"Promising",value:count(run?.promising_jobs)},{label:"Semantic analysis",value:`${run?.semantic_completed??0} / ${run?.semantic_selected??0}`},{label:"Ranked",value:count(run?.ranked_jobs)},{label:"Companies",value:count(run?.companies_represented)}];
 return <section className="find-jobs panel"><div className="find-jobs-heading"><div><p className="panel-label">FIND JOBS</p><h2>Turn your approved profile into ranked opportunities.</h2><p>Searches a bounded starter universe of supported public employer sources, plus companies you choose to watch. AI analysis is bounded and may use provider credits.</p></div><button className="cta" type="button" disabled={pending||active} onClick={find}><Search size={16}/>{active?"FINDING JOBS...":"FIND JOBS"}</button></div>
 {sources.length?<div className="configured-sources"><span>{sources.length} active source{sources.length===1?"":"s"}; starter sources are selected automatically</span>{sources.slice(0,4).map(source=><b key={source.id}>{source.company}</b>)}</div>:null}
 <details className="first-source"><summary><Building2 size={20}/> Want RoleCall to watch a specific company?</summary><p>This is optional. Find Jobs works with the starter employer universe without manual setup.</p><form onSubmit={addSource}><input name="company" aria-label="Company name" placeholder="Company name" required/><input name="careers_url" aria-label="Public careers page URL" type="url" placeholder="https://company.com/careers" required/><button type="submit" disabled={adding}>{adding?"DETECTING...":"ADD COMPANY"}</button></form></details>
 {run?<><div className="intelligence-progress">{steps.map(step=><div key={step.label}><span>{step.label}</span><strong>{step.value}</strong></div>)}</div><p className={`status-line ${run.status}`} role="status"><RefreshCw size={14}/>{run.message}{run.provider?` · ${run.provider}/${run.model} · $${run.estimated_cost.toFixed(4)}`:" · deterministic scoring remains available"}</p></>:null}{message?<p className="status-line" role="status">{message}{pollingStopped?<button type="button" onClick={()=>{setPollingStopped(false);pollFailures.current=0;startTransition(()=>router.refresh())}}>REFRESH STATUS</button>:null}</p>:null}</section>
}
