"use client";
import {FormEvent,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {DatabaseZap,Plus,RefreshCw,Trash2} from "lucide-react";
import {apiFetch} from "@/lib/client-api";
import {JobSource,ScanRun} from "@/lib/types";

export default function SourceManager({sources,scans}:{sources:JobSource[];scans:ScanRun[]}){
 const router=useRouter();const [pending,startTransition]=useTransition();const [showAdd,setShowAdd]=useState(false);const [status,setStatus]=useState("");
 async function request(path:string,options?:RequestInit){setStatus("");const response=await apiFetch(path,options);if(!response.ok)throw new Error(await response.text());return response.status===204?null:response.json()}
 function refresh(){startTransition(()=>router.refresh())}
 async function scanAll(){setStatus("Scanning enabled sources…");try{const run=await request("/sources/scan-all",{method:"POST"});setStatus(`Scan ${run.status}: ${run.jobs_added} new, ${run.jobs_scored} scored`);refresh()}catch{setStatus("Scan failed. Check source errors and backend connectivity.")}}
 async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await request("/sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({company:form.get("company"),ats_type:form.get("ats_type"),board_identifier:form.get("board_identifier"),careers_url:form.get("careers_url")||null,enabled:true,scan_frequency:"manual"})});setShowAdd(false);refresh()}catch{setStatus("Could not add source.")}}
 async function toggle(source:JobSource){await request(`/sources/${source.id}/enabled`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:!source.enabled})});refresh()}
 async function scan(id:number){setStatus("Scanning source…");try{const run=await request(`/sources/${id}/scan`,{method:"POST"});setStatus(`Scan ${run.status}: ${run.jobs_added} new jobs`);refresh()}catch{setStatus("Source scan failed.")}}
 async function remove(id:number){if(!window.confirm("Delete this source configuration? Jobs already discovered are preserved."))return;await request(`/sources/${id}`,{method:"DELETE"});refresh()}
 const latest=scans[0];return <div className="source-manager">
 <section className="scan-command"><div><p className="eyebrow">SCAN COMMAND CENTER</p><h2>Operational discovery loop</h2><p>Fetch, normalize, classify, filter, deduplicate, and family-score every enabled source.</p></div><button disabled={pending} className="scan-all" onClick={scanAll}><RefreshCw size={16}/>SCAN ALL SOURCES</button></section>
 {status?<p className="status-line" role="status">{status}</p>:null}
 {latest?<section className="scan-metrics">{[["Sources",latest.source_count],["Successful",latest.successful_source_count],["Failed",latest.failed_source_count],["Fetched",latest.jobs_fetched],["Filtered",latest.jobs_filtered],["Duplicates",latest.jobs_deduplicated],["New jobs",latest.jobs_added],["Scored",latest.jobs_scored],["Exceptional",latest.exceptional_count],["Strong",latest.strong_count]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>:null}
 <div className="source-heading"><div><h2>Sources</h2><span>{sources.length} configured</span></div><button onClick={()=>setShowAdd(x=>!x)}><Plus size={15}/> ADD SOURCE</button></div>
 {showAdd?<form className="source-form" onSubmit={add}><label>Company<input name="company" required/></label><label>Source type<select name="ats_type"><option>greenhouse</option><option>lever</option><option>ashby</option><option>smartrecruiters</option><option>workday</option><option>generic_company_site</option><option>icims</option><option>jobvite</option><option>successfactors</option></select></label><label>Board identifier<input name="board_identifier" required/></label><label>Careers URL<input name="careers_url" type="url"/></label><button type="submit">SAVE SOURCE</button></form>:null}
 <section className="source-table"><div className="source-row source-labels"><span>Company / board</span><span>ATS</span><span>Last scan</span><span>Jobs</span><span>Status</span><span>Actions</span></div>{sources.map(source=><div className="source-row" key={source.id}><div><strong>{source.company}</strong><small>{source.board_identifier}</small></div><span>{source.ats_type}</span><span>{source.last_scanned_at?new Date(source.last_scanned_at).toLocaleString():"Never"}</span><span>{source.jobs_discovered_total}</span><button className={`toggle ${source.enabled?"enabled":""}`} onClick={()=>toggle(source)}>{source.enabled?"ENABLED":"DISABLED"}</button><div className="source-actions"><button aria-label={`Scan ${source.company}`} onClick={()=>scan(source.id)}><DatabaseZap size={14}/></button><button aria-label={`Delete ${source.company}`} onClick={()=>remove(source.id)}><Trash2 size={14}/></button></div>{source.last_error?<p className="source-error">{source.last_error}</p>:null}</div>)}</section>
 <section className="scan-history panel"><p className="panel-label">RECENT RUNS</p>{scans.length?scans.slice(0,8).map(run=><div key={run.id}><span>#{run.id} · {new Date(run.started_at).toLocaleString()}</span><b>{run.status}</b><span>{run.jobs_added} added / {run.jobs_scored} scored</span></div>):<p>No scans recorded.</p>}</section>
 </div>
}
