import Link from "next/link";
import {ArrowRight,BrainCircuit,DatabaseZap,Github,LockKeyhole,SearchCheck,Sparkles} from "lucide-react";

export default function Landing(){return <div className="landing">
  <section className="landing-hero"><p className="eyebrow">OPEN-SOURCE PERSONAL CAREER INTELLIGENCE</p><h1>Find the jobs worth<br/> <span>your attention.</span></h1><p className="hero-copy">A resume-aware agent that discovers roles, explains the evidence behind each match, surfaces real gaps, respects your constraints, and helps you take the right next step.</p><div className="hero-actions"><Link className="cta" href="/onboarding">Get started <ArrowRight size={17}/></Link><a className="secondary-cta" href="#open-source"><Github size={17}/> View GitHub</a></div><div className="hero-proof"><span>Evidence-grounded</span><span>Constraint-aware</span><span>Self-hostable</span></div></section>
  <section className="product-preview"><div className="preview-head"><span>OPPORTUNITY RADAR</span><b>3 worth your attention</b></div>{[["Search Research Engineer","APPLY NOW","88"],["Applied ML Scientist","APPLY","76"],["AI Platform PM","CONTACT FIRST","63"]].map(item=><article key={item[0]}><div><small>EXAMPLE COMPANY</small><strong>{item[0]}</strong><p>Matched from verified experience · one evidence gap</p></div><em>{item[1]}</em><b>{item[2]}</b></article>)}</section>
  <section className="landing-section"><p className="eyebrow">HOW IT WORKS</p><h2>From noisy listings to clear decisions.</h2><div className="feature-grid">{[[SearchCheck,"Discover","Scan public ATS and company sources, normalize duplicates, and prioritize fresh roles."],[DatabaseZap,"Understand you","Connect every recommendation to verified resume evidence and explicit preferences."],[BrainCircuit,"Reason","Separate true experience gaps from wording gaps and genuinely unknown information."],[Sparkles,"Act","Recommend apply, contact-first, or stretch—and assist with materials when requested."]].map(([Icon,title,copy])=><article key={String(title)}><Icon size={22}/><h3>{String(title)}</h3><p>{String(copy)}</p></article>)}</div></section>
  <section className="landing-section open-source" id="open-source"><LockKeyhole size={28}/><div><p className="eyebrow">PRIVATE BY DESIGN</p><h2>Local-first. Inspectable. Yours.</h2><p>Run it locally or self-host it. Candidate data lives in ignored local configuration while the public repository ships only fictional examples.</p></div><Link href="/dashboard">Explore the dashboard <ArrowRight size={16}/></Link></section>
</div>}
