export type Recommendation = "exceptional" | "strong" | "possible" | "weak" | "skip";

export interface Job {
  id: number; external_id: string; source: string; company: string; title: string; location: string | null;
  remote_type: string; employment_type: string | null; salary_min: number | null; salary_max: number | null;
  salary_currency: string | null; description: string; requirements: string[]; preferred_qualifications: string[];
  apply_url: string; source_url: string; posted_at: string | null; discovered_at: string;
  fit_score: number | null; fit_explanation: string | null; matched_skills: string[]; missing_skills: string[];
  recommendation: Recommendation | null; application_status: string | null;
  component_scores: Record<string,{score:number;weight:number;explanation:string}>; strengths: string[]; gaps: string[];
  human_label: "excellent"|"good"|"maybe"|"poor"|null; human_notes:string|null;
  role_family:string;role_family_confidence:number;role_family_reasons:string[];classification_method:string;deterministic_family:string|null;deterministic_confidence:number|null;semantic_family:string|null;semantic_confidence:number|null;final_family:string|null;classification_resolution_method:string|null;family_fit_score:number|null;family_component_scores:Record<string,{score:number;weight:number;explanation:string}>;matched_evidence_ids:string[];career_transition_flag:boolean;career_transition_notes:string|null;raw_company:string|null;canonical_company:string|null;normalized_location:string|null;alternate_sources:{source:string;source_url:string}[];
  opportunity_score:OpportunityScore|null;semantic_fit_score:number|null;semantic_fit_confidence:number|null;semantic_analysis_status:string;semantic_provider:string|null;semantic_model:string|null;semantic_estimated_cost:number;
  first_seen_at:string|null;last_seen_at:string|null;last_verified_at:string|null;posting_status:string;posting_confidence:"HIGH"|"MEDIUM"|"LOW"|"UNKNOWN";posting_confidence_reason:string;
}

export interface OpportunityScore {overall_score:number;deterministic_fit:number|null;semantic_fit:number|null;technical_fit:number|null;career_fit:number|null;research_fit:number|null;skills_fit:number|null;location_fit:number|null;compensation_fit:number|null;visa_fit:number|null;freshness_score:number|null;application_effort_score:number|null;confidence:number;recommendation:"APPLY_NOW"|"APPLY"|"CONTACT_FIRST"|"STRETCH"|"SKIP";recommendation_reason:string;why_you_match:{reason:string;evidence_ids:string[]}[];real_gaps:{text:string;kind:"EXPERIENCE_GAP"|"EVIDENCE_OR_WORDING_GAP"|"UNKNOWN_NEEDS_CLARIFICATION"}[];constraints:{location:"MATCH"|"MISMATCH"|"UNKNOWN";work_arrangement:"MATCH"|"MISMATCH"|"UNKNOWN";compensation:"MATCH"|"MISMATCH"|"UNKNOWN";visa:"MATCH"|"MISMATCH"|"UNKNOWN";employment_type:"MATCH"|"MISMATCH"|"UNKNOWN";seniority:"MATCH"|"MISMATCH"|"UNKNOWN";hard_blockers:string[]}}
export interface CareerRun{id:number;status:string;stage:string;source_count:number;sources_scanned:number;sources_succeeded:number;sources_failed:number;companies_represented:number;jobs_found:number;unique_jobs:number;promising_jobs:number;semantic_selected:number;semantic_completed:number;semantic_failed:number;ranked_jobs:number;provider:string|null;model:string|null;estimated_cost:number;message:string;errors:{error:string}[];started_at:string|null;completed_at:string|null}

export interface JobList { items: Job[]; total: number; counts: {scanned:number; passing_filters:number; strong:number; exceptional:number; ready:number} }
export interface EvidenceRecord {id:string;category:string;sub_category:string;statement:string;source:string;source_reference:string;company:string|null;role:string|null;skills:string[];domains:string[];verified:boolean;confidence:number}
export interface ProfileItem {value:string;details:Record<string,string>;evidence_ids:string[]}
export interface CandidateProfile {identity:{name:string;legal_name:string;email:string;phone:string;location:string;evidence_ids:string[]};professional_summary:ProfileItem;roles:ProfileItem[];experience:ProfileItem[];education:ProfileItem[];skills:ProfileItem[];research:ProfileItem[];publications:ProfileItem[];patents:ProfileItem[];projects:ProfileItem[];technical_domains:ProfileItem[];leadership:ProfileItem[];portfolio_url:string;linkedin_url:string}
export interface JobSource {id:number;company:string;ats_type:string;board_identifier:string;careers_url:string|null;enabled:boolean;scan_frequency:string;last_scanned_at:string|null;last_success_at:string|null;last_error:string|null;jobs_discovered_total:number;created_at:string;updated_at:string}
export interface ScanRun {id:number;started_at:string;completed_at:string|null;status:string;source_count:number;successful_source_count:number;failed_source_count:number;jobs_fetched:number;jobs_filtered:number;jobs_deduplicated:number;jobs_added:number;jobs_updated:number;jobs_scored:number;exceptional_count:number;strong_count:number;possible_count:number;weak_count:number;skip_count:number;errors_json:{company?:string;error:string}[];duration_seconds:number|null}
export interface Company {id:number;name:string;canonical_name:string;website_url:string|null;careers_url:string|null;company_type:string;priority:string;enabled:boolean;notes:string|null;detected_ats:string|null;created_at:string;updated_at:string;source_count:number;last_scan:string|null}
export interface SemanticFitReport {job_id:number;role_family:string;semantic_fit_score:number;confidence:number;strengths:{statement:string;evidence_ids:string[]}[];gaps:string[];requirement_matches:{requirement:string;assessment:string;evidence_ids:string[]}[];requirement_gaps:string[];evidence_ids:string[];career_transition_analysis:string|null;research_alignment:string;technical_alignment:string;experience_alignment:string;recommended_action:string;reasoning_summary:string;unsupported_claims:string[];requires_human_review:boolean;deterministic_score:number|null;blended_score:number|null;provider:string;model:string;prompt_version:string;latency_ms:number;input_tokens:number;output_tokens:number;cached_tokens:number;estimated_cost:number;cache_hit:boolean;created_at:string}
export interface ResearchSource {url:string;title:string;source_type:string;retrieved_at:string;excerpt:string}
export interface JobResearchReport {job_id:number;company_summary:string;role_summary:string;likely_team_context:string;key_requirements:string[];preferred_requirements:string[];research_relevance:string;technical_relevance:string;career_opportunity:string;potential_risks:string[];questions_to_investigate:string[];source_citations:ResearchSource[];provider:string;model:string;prompt_version:string;latency_ms:number;input_tokens:number;output_tokens:number;cached_tokens:number;estimated_cost:number;cache_hit:boolean;generated_at:string}
export interface AgentRun {id:number;agent_type:string;objective:string;job_id:number|null;status:string;actions_json:{step?:number;tool?:string;status?:string;result_count?:number}[];errors_json:{error:string}[];provider:string|null;model:string|null;prompt_version:string|null;evidence_ids_used:string[];sources_used:string[];input_tokens:number;output_tokens:number;cached_tokens:number;estimated_cost:number;latency_ms:number;started_at:string|null;completed_at:string|null;requires_human_review:boolean}
export interface GroundedText{text:string;evidence_ids:string[]}
export interface ResumeBullet{id:string;section:string;employer_or_context:string;generated_text:string;source_evidence_ids:string[];source_resume_text:string;transformation_type:string;validation_status:string;validation_confidence:number;edited_text:string|null}
export interface ApplicationAnswer{id:string;question_text:string;detected_category:string;answer:string|null;answer_status:string;answer_type:string;evidence_ids:string[];confidence:number;character_limit:number|null;requires_human_review:boolean;reusable:boolean}
export interface ApplicationPackage{id:number;job_id:number;status:string;resume_version_id:string;resume_strategy:{primary_positioning:string;top_3_themes:string[];known_gaps:string[];cover_letter_recommended:boolean;application_risk:string};tailored_resume_path:string|null;tailored_resume_preview:{summary:GroundedText[];bullets:ResumeBullet[];skills:GroundedText[]};cover_letter:string|null;cover_letter_status:string;application_answers:ApplicationAnswer[];application_summary:GroundedText[];evidence_ids_used:string[];unsupported_claims_removed:string[];review_findings:{severity:string;affected_artifact:string;claim:string;evidence_ids:string[];recommended_action:string}[];review_status:string|null;requires_human_review:boolean;human_review_reasons:string[];provider:string;model:string;prompt_versions:Record<string,string>;input_tokens:number;output_tokens:number;cached_tokens:number;estimated_cost:number;latency_ms:number;approved_at:string|null}
export interface EligibilityDecision{eligibility:"ELIGIBLE"|"ELIGIBLE_LOW_CONFIDENCE"|"NEEDS_REVIEW"|"BLOCKED"|"SKIP";priority:number;reasons:string[];hard_blockers:string[];manual_override:boolean}
export interface ApplicationFormField{field_id:string;label:string;field_type:string;required:boolean;detected_category:string;mapped_answer_source:string|null;mapped_answer:string|null;requires_human_review:boolean;write_allowed:boolean}
export interface SubmitControl{selector_strategy:string;locator_value:string|null;accessible_name:string;element_type:string;visible:boolean;enabled:boolean;actionable:boolean}
export interface ApplicationForm{application_url:string;ats:string;fields:ApplicationFormField[];required_fields:string[];submit_controls:SubmitControl[];captcha_detected:boolean;authentication_required:boolean;status:string}
export interface BrowserRunResult{status:string;eligibility:EligibilityDecision|null;form:ApplicationForm|null;fields_resolved:number;fields_needing_review:number;resume_upload_status:string;ready_to_submit:boolean;blockers:string[];submitted:boolean;confirmation_url:string|null;failure_stage:string|null;error_code:string|null;external_click_occurred:boolean;confirmation_verified:boolean;receipt_created:boolean;retry_allowed:boolean;diagnostics:Record<string,unknown>}
export interface ApplicationSettings{application_mode:"manual"|"fill_only"|"auto_submit";auto_submit_enabled:boolean;auto_apply_paused:boolean;policy:{enabled:boolean;allowed_role_families:string[];daily_application_cap:number;company_daily_cap:number;apply_to_moderate_fit:boolean;allow_unknown_salary:boolean}}
export interface ApplicationSummary{discovered:number;eligible:number;packages_ready:number;queued:number;filled:number;submitted:number;needs_review:number;blocked:number;failed:number;estimated_llm_cost:number}
export interface MorningReport{period_start:string;period_end:string;jobs_discovered:number;semantic_analyses:number;packages_generated:number;applications_queued:number;applications_submitted:number;applications_blocked:number;applications_needing_review:number;applications_failed:number;captchas:number;duplicate_prevented:number;estimated_openai_cost:number}
export interface OperationsStatus{autonomy_paused:boolean;heartbeats:Record<string,{status:string;last_heartbeat_at:string;last_success_at:string|null}>}
export interface ContactEvidence{source_url:string;source_type:string;statement:string}
export interface ContactRead{contact_id:number;job_id:number;name:string;current_title:string;company:string;public_profile_url:string;source_type:string;source_url:string;team:string|null;domains:string[];location:string|null;role_similarity:number;team_similarity:number;domain_similarity:number;company_match:boolean;seniority_usefulness:number;location_relevance:number;relevance_score:number;relevance_reason:string;relationship_status:"VERIFIED"|"LIKELY_RELEVANT"|"UNKNOWN";relationship_confidence:number;evidence:ContactEvidence[];discovered_at:string;last_checked_at:string}
export interface ContactList{items:ContactRead[];status:string;message:string|null;sources_checked:number;pages_checked:number;candidates_discovered:number;cached:boolean}
